S00009コーディング_red
for-training2023/webA pull request #2
Opened 2023-06-07 02:31 UTC by s-nanami

S00009のコーディングの講師レビューをお願いいたします。

2023-06-22 08:22 UTC, yukino-furuhashi commented
確認しました。
指摘箇所にコメントをつけているので、確認・対応をお願いします。

2023-06-26 01:12 UTC, yukino-furuhashi requested changes
すみません、指摘コメントが反映されていませんでした。
コメントした部分のご確認をお願いいたします。

2023-06-26 02:39 UTC, s-nanami commented
@yukino-furuhashi 
指摘点を修正しました。お手隙の際にご確認お願いいたします。

2023-06-28 07:06 UTC, yukino-furuhashi commented
OKです。masterにマージします。

2023-06-28 07:07 UTC, merged