Dev yokoi
for-training2023/webA pull request #4
Opened 2023-06-16 08:48 UTC by MasatoYokoi

S00004のコーディング完了したので講師の方レビューお願いいたします。

2023-06-27 02:08 UTC, yukino-furuhashi requested changes
確認しました。
指摘箇所にコメントしていますので、確認・対応をお願いします。

2023-06-27 02:08 UTC, yukino-furuhashi commented on src/main/webapp/ja/S00004.jsp
> +									<img alt="title" class = "a" src="/webA/images/<%=record.getImage_file_name() %>">
画面設計書には画像の処理についての記載があります。
画面レイアウトに合わせて適切に「拡大」もしくは「縮小」して表示する必要があるのですが、
その処理がないように見受けられます。
（共通機能として別ブランチで実装しているなら問題ないのでこのコメントは無視してください）

2023-06-27 08:40 UTC, MasatoYokoi commented on src/main/java/jp/excd/servlet/S00004.java
> +			}
77行目のコメント修正しました。
404遷移はS00004.javaの223行目にて処理を行っています。

2023-06-27 08:40 UTC, MasatoYokoi commented on src/main/java/jp/excd/servlet/S00004.java
> +
詳細設計を修正し、doPostメソッドをなくしました。
OwnCloudの成果物に最新の詳細設計をアップロードし直したので確認お願いいたします。

2023-06-27 08:40 UTC, MasatoYokoi commented on src/main/webapp/ja/S00004.jsp
> +						<% if(composerList.get(0).getTitle() == null ){ %>
S00004.jspの128行目にコメントを入れておきました。

2023-06-27 08:40 UTC, MasatoYokoi commented on src/main/webapp/ja/S00004.jsp
> +									<img alt="title" class = "a" src="/webA/images/<%=record.getImage_file_name() %>">
S00004.jspの23～29行目にて処理を行っています。

2023-06-27 08:40 UTC, MasatoYokoi commented
ご指摘していただいた点の修正完了しました。
再度ご確認のほど宜しくお願い致します。

2023-06-29 00:44 UTC, yukino-furuhashi commented
OKです。masterにマージします。

2023-06-29 00:44 UTC, merged